
environments:
  - slug: preview
    name: preview
    env_files:
      - .env.example
      - .env.example.preview
    playwright_projects_match:
      - '*'

  - slug: production
    name: production
    env_files:
      - .env.example
      - .env.example.production
    playwright_projects_match:
      - '*'
    scheduled_trigger: 30 12 * * *
